In [ ]:
#import python libraries
import numpy as np
import pandas as pd
from datetime import datetime
!pip install yfinance
import yfinance as yf
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')


import seaborn as sns
from scipy import stats
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.79-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.4.4)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.3 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.79

In [ ]:
#read price data from csv
url = "https://raw.githubusercontent.com/PhaNtazM1337/CTC22/main/Price%20Data.csv"
raw_data = pd.read_csv(url, header=0, index_col=0)

#build stock tickers/symbols list
assets = list(raw_data)
#Initialize randomized weights/fractional holdings
weights = np.random.rand(40)
weights = weights/np.sum(weights)
raw_data.head()

,YPA,AOX,KWE,VSR,VWR,ZNX,MWN,MZJ,VEO,GJA,...,OWG,YLF,CPM,TGI,MGW,NTR,KKD,JPN,CGS,VOX
Ticker,,,,,,,,,,,,,,,,,,,,,
Basic shares outstanding,9.373689e+06,1.383451e+09,4.004248e+09,1.453021e+09,1.799252e+08,6.498459e+08,1.607075e+10,45460884.00,87838044.00,8.603094e+08,...,2.617854e+08,60026348.00,59555617.00,1.587486e+09,7.036254e+08,1.078783e+08,7.730925e+08,1.529113e+08,1.044490e+09,4.633696e+08
10/5/20,2.426000e+02,1.379300e+02,7.020000e+00,3.096000e+01,1.193000e+01,1.312000e+01,1.165000e+02,270.69,100.80,6.060000e+01,...,4.728000e+01,342.87,102.03,1.129000e+01,3.219300e+02,4.679000e+01,2.166400e+02,1.418933e+02,5.747000e+01,3.922000e+01
10/6/20,2.426200e+02,1.357000e+02,6.980000e+00,3.040000e+01,1.200000e+01,1.253000e+01,1.131600e+02,264.82,100.86,6.040000e+01,...,4.693000e+01,339.28,101.42,1.126000e+01,3.150400e+02,4.561000e+01,2.143400e+02,1.379933e+02,5.666000e+01,3.976000e+01
10/7/20,2.397200e+02,1.370100e+02,7.230000e+00,3.162000e+01,1.224000e+01,1.307000e+01,1.150800e+02,268.54,101.56,6.112000e+01,...,4.865000e+01,351.83,104.00,1.121000e+01,3.133100e+02,4.715000e+01,2.195300e+02,1.417667e+02,5.610000e+01,4.008000e+01
10/8/20,2.403300e+02,1.378500e+02,7.350000e+00,3.221000e+01,1.273000e+01,1.316000e+01,1.149700e+02,271.20,103.69,6.260000e+01,...,4.944000e+01,359.53,101.06,1.136000e+01,3.153200e+02,4.743000e+01,2.190300e+02,1.419733e+02,5.722000e+01,3.985000e+01

In [ ]:
#create dataframe to store close price of stocks
df = raw_data.drop(labels=["Basic shares outstanding"])
df

,YPA,AOX,KWE,VSR,VWR,ZNX,MWN,MZJ,VEO,GJA,...,OWG,YLF,CPM,TGI,MGW,NTR,KKD,JPN,CGS,VOX
Ticker,,,,,,,,,,,,,,,,,,,,,
10/5/20,242.600006,137.929993,7.02,30.959999,11.93,13.12,116.50,270.69,100.80,60.60,...,47.28,342.87,102.03,11.290,321.93,46.79,216.64,141.8933,57.47,39.22
10/6/20,242.619995,135.699997,6.98,30.400000,12.00,12.53,113.16,264.82,100.86,60.40,...,46.93,339.28,101.42,11.260,315.04,45.61,214.34,137.9933,56.66,39.76
10/7/20,239.720001,137.009995,7.23,31.620001,12.24,13.07,115.08,268.54,101.56,61.12,...,48.65,351.83,104.00,11.210,313.31,47.15,219.53,141.7667,56.10,40.08
10/8/20,240.330002,137.850006,7.35,32.209999,12.73,13.16,114.97,271.20,103.69,62.60,...,49.44,359.53,101.06,11.360,315.32,47.43,219.03,141.9733,57.22,39.85
10/9/20,242.289993,138.440002,7.25,32.160000,12.52,13.20,116.97,273.56,103.99,63.29,...,48.86,366.00,99.88,11.570,314.63,48.08,222.82,144.6667,56.31,40.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/29/21,398.359985,152.300003,14.30,52.930000,50.58,21.01,142.83,329.51,135.22,128.27,...,99.79,495.00,123.91,9.850,332.78,57.17,302.62,260.4367,83.79,56.09
9/30/21,394.179993,150.410004,14.16,52.709999,48.94,20.52,141.50,325.52,132.18,128.73,...,98.49,495.75,119.66,9.860,330.57,56.14,299.41,258.4933,82.40,56.26
10/1/21,389.359985,150.949997,14.16,53.130001,49.77,21.65,142.65,323.33,132.47,129.13,...,97.65,505.61,121.25,10.105,333.57,56.79,302.49,258.4067,83.85,57.65
10/4/21,391.279999,150.199997,14.35,53.980000,49.18,21.39,139.14,313.87,130.26,125.20,...,96.78,494.60,121.88,10.360,334.16,56.52,289.25,260.5100,83.73,57.58
10/5/21,404.500000,151.089996,14.29,54.340000,49.05,21.47,141.11,332.47,129.69,128.07,...,98.70,498.09,122.57,10.580,330.76,56.24,293.35,260.1967,81.74,57.94

In [ ]:
#create dataframe to store close price of stocks
returns = df.pct_change()
returns

In [ ]:
#Create and show the covariance matrix
cov_matrix_annual = df.pct_change().apply(lambda x: np.log(1+x)).cov() * 252
cov_matrix_annual

In [ ]:
port_variance = np.dot(weights.T, np.dot(cov_matrix_annual, weights))
port_variance

0.032847579060861706

In [ ]:
port_volatility = np.sqrt(port_variance)
port_volatility

0.18123901086924335

In [ ]:
port_annual_return = np.sum(returns.mean() * weights) * 252
port_annual_return

0.4886027727656581

In [ ]:
port_sharpe = port_annual_return / port_volatility
port_sharpe

2.695902887696542

In [ ]:
num_ports = 5000
all_weights = np.zeros((num_ports, 40))
ret_arr = np.zeros(num_ports)
vol_arr = np.zeros(num_ports)
sharpe_arr = np.zeros(num_ports)
log_return = np.log(df/df.shift(1))
for ind in range(num_ports): 
    # weights 
    weights = np.array(np.random.random(40)) 
    weights = weights/np.sum(weights)  
	
    # save the weights
    all_weights[ind,:] = weights
	
    # expected return 
    ret_arr[ind] = np.sum((log_return.mean()*weights)*252)

    # expected volatility 
    vol_arr[ind] = np.sqrt(np.dot(weights.T,np.dot(log_return.cov()*252, weights)))

    # Sharpe Ratio 
    sharpe_arr[ind] = ret_arr[ind]/vol_arr[ind]

In [ ]:
# plot the data
plt.figure(figsize=(12,8))
plt.scatter(vol_arr,ret_arr,c=sharpe_arr,cmap='plasma')
plt.colorbar(label='Sharpe Ratio')
plt.xlabel('Volatility')
plt.ylabel('Return')

In [ ]:
sharpe_arr.argmax()
print(max(sharpe_arr))

In [ ]:
all_weights[1074,:]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!python "/content/drive/MyDrive/ColabNotebooks/backtesting-main/backtest_v2/demo.py"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
python3: can't open file '/content/drive/MyDrive/ColabNotebooks/backtesting-main/backtest_v2/demo.py': [Errno 2] No such file or directory

In [ ]:
#Calculate CAPM: Expected Return = beta * (expected market return)


# Normalize stock data based on initial price
def normalize(df):
  x = df.copy()
  for i in x.columns[1:]:
    x[i] = x[i]/x[i][0]
  return x

normalize(df)

# Function to plot interactive plot
def interactive_plot(df, title):
  fig = px.line(title = title)
  for i in df.columns[1:]:
    fig.add_scatter(x = df['Ticker'], y = df[i], name = i)
  fig.show()

interactive_plot(normalize(df), 'Normalized Prices')

In [ ]:
#Daily Return function:
def daily_return(df):
  df_daily_return = df.copy()
  for i in df.columns[1:]:
      for j in range(1, len(df)):
          df_daily_return[i][j] = ((df[i][j]- df[i][j-1])/df[i][j-1]) * 100
      df_daily_return[i][0] = 0
  return df_daily_return

stocks_daily_return = daily_return(df)
stocks_daily_return

# Histogram of daily returns (in %)
stocks_daily_return.boxplot(figsize=(12, 10), grid=False)
plt.title("Daily returns of the stocks")

In [ ]:
# Initialize empty dictionaries to save results
beta,alpha = dict(), dict()
# Make a nice subplot
fig, axes = plt.subplots(1,3, dpi=150, figsize=(15,8))
axes = axes.flatten()
# Loop on every stock daily return
for idx, stock in enumerate(stocks_daily_return.columns):
# Ignoring the date and Market Columns 
    if stock != "Date" and stock != "Market":
        # scatter plot between stock and the Market
        stocks_daily_return.plot(kind = "scatter", x = "Market", y = stock, ax=axes[idx-1])
 
        # Fit a line (regression using polyfit of degree 1)
        b_, a_ = np.polyfit(stocks_daily_return[stock], stocks_daily_return["Market"], 1)
 
        regression_line = b_ * stocks_daily_return["Market"] + a_
        axes[idx-1].plot(stocks_daily_return["Market"], regression_line, "-", color = "r")
        # save the regression coeeficient for the current stock
        beta[stock] = b_
        alpha[stock] = a_
plt.suptitle("Beta estimation: regression between Market and individual stock daily performance", size=20)

In [ ]:
# Initialize the expected return dictionary
ER = dict()
rf = 0 # assume risk-free rate is zero in this case
# Estimate the expected return of the market using the daily returns
rm = stocks_daily_return["Market"].mean() * 253